services:
  db:
    image: postgres:14-alpine
    container_name: db_service
    environment:
      - POSTGRES_HOST_AUTH_METHOD: ${PG_HOST_AUTH_METHOD}
      - POSTGRES_USER: ${DB_USER}
      - POSTGRES_PASSWORD: ${DB_PASSWORD}
      - POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./django_project
    container_name: backend_service
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/user/src/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend_service
    volumes:
      - ./frontend:/user/src/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data:
