# Generated by Django 5.1.3 on 2024-11-11 22:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='medications_name_63d0af_idx')],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/medications/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('form', models.CharField(choices=[('tablet', 'Tablet'), ('capsules', 'Capsules'), ('topical', 'Topical'), ('drops', 'Drops'), ('suppositories', 'Suppositories'), ('inhalers', 'Inhalers'), ('injections', 'Injections'), ('others', 'Others')], max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('expiry_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='medications.category')),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['id', 'slug'], name='medications_id_581882_idx'), models.Index(fields=['name'], name='medications_name_0c05c3_idx'), models.Index(fields=['-created_at'], name='medications_created_6d751b_idx')],
            },
        ),
    ]
