# Generated by Django 5.1.3 on 2024-11-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ('name',), 'verbose_name': 'Medication', 'verbose_name_plural': 'Medications'},
        ),
        migrations.AlterField(
            model_name='medication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medications/'),
        ),
    ]
