# Generated by Django 5.1.3 on 2024-11-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='image',
            field=models.ImageField(blank=True, default='static/imgs/default.png', null=True, upload_to='medications/'),
        ),
    ]
