# Generated by Django 5.1.3 on 2024-11-12 18:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_refillrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refillrequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
