# Generated by Django 5.1.3 on 2024-11-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_alter_refillrequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refillrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
