# Generated by Django 5.1.3 on 2024-11-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0006_alter_refillrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
